Спринт 9
Elena-Zarya/java-filmorate pull request #2
Opened 2023-03-11 01:45 UTC by Elena-Zarya

2023-03-11 15:10 UTC, mikita95 requested changes
Все сделано отлично :) Нужно только исправить пару моментов.

2023-03-11 15:10 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmStorage filmStorage;
Может быть final - ссылка не меняется

2023-03-11 15:10 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserStorage userStorage;
Вы сделали UserStorage - `@Component` - то есть он уже создан в контексте спринга. Можно не создавать его вручную, а просто передать через аргумент конструктора - спринг сам его заинжектит.
Также можно поступить и с FilmStorage.
Можно поле сделать final - оно не меняется

2023-03-11 15:10 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException{
Не хватает пробела перед скобкой

2023-03-11 15:10 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FutureCustomValidator.java
> +public class FutureCustomValidator implements ConstraintValidator<FutureCustom, LocalDate> {
Отличное решение!

2023-03-11 15:10 UTC, mikita95 commented on src/test/java/ru/yandex/practicum/filmorate/FilmTest.java
> +        private static Validator validator;
Неверные отступы здесь :)

2023-03-11 15:10 UTC, mikita95 commented on src/test/java/ru/yandex/practicum/filmorate/UserTest.java
> +    static {
Можно инициализировать в @BeforeAll - так более единообразно

2023-03-13 10:23 UTC, Elena-Zarya commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserStorage userStorage;
Пробовала написать в конструкторе 
AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext();
        userStorage = ctx.getBean(UserStorage.class);
Выдает исключение. Так и не поняла как правильно прописать, чтоб работало. В итоге добавила эту аннотацию, тесты прошли. Насколько это хорошее решение?

2023-03-14 07:37 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-03-14 07:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserStorage userStorage;
Это решение хорошее :) Однако, не рекомендуется использовать Autowired над полями, так сложнее тестировать, иногда можно не сработать. Лучше всего обозначить поле final и сделать конструктор, тогда у спринга не будет выбора как собрать объект.
```
@RestController
public class UserController {
    private final UserStorage userStorage;
    // Здесь можно писать, а можно не писать @Autowired - спринг и так поймет, так как вариантов нет других
    public UserController(UserStorage userStorage) {
        this.userStorage = userStorage;
    }
    ...
```
А если мы используем ломбок, но тогда можно так
```
@RestController
@ReqArgsConstructor
public class UserController {
    private final UserStorage userStorage;
    ...
```

2023-03-15 04:33 UTC, merged