11 спринт
Elena-Zarya/java-filmorate pull request #4
Opened 2023-04-23 23:33 UTC by Elena-Zarya

2023-04-24 18:54 UTC, mikita95 requested changes
Все сделано очень хорошо. Оставил лишь несколько небольших замечаний

2023-04-24 18:54 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +                    jdbcTemplate.update("INSERT INTO film_likes (film_id, user_id) VALUES (?, ?)", filmId, userId);
Предполагается, что метод PUT (в данном случае addLike) должен быть идемпотентным (то есть несколько вызовов одного и того же метода с одними параметрами, имеет такой же эффект как и один вызов): https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT. В данном случае можно просто поменять sql-запрос, использовав команду merge в H2 (https://www.h2database.com/html/commands.html#merge_into) - если запись существует, то это сработает как update, иначе произойдет insert.
Конечно, понятие идемпотентности предполагает в большей степени именно влияние на состояние сервера, а не клиента, и в данном случае состояние не изменится (так как данные не поменяются). Но с точки зрениея клиента - это не ошибка, поставить повторно лайк фильму.
Вы отлично сделали, что в начале проверяете существование записи, поэтому сейчас все верно. Единственное, что можно было бы использовать команду merge, чтобы не выполнять лишние запросы

2023-04-24 18:54 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmDbService.java
> +    FilmStorage filmStorage;
Не хватает модификатора доступа

2023-04-25 15:09 UTC, Elena-Zarya commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        String sqlQueryFilms = "SELECT film_id, film_name, description, duration, release_date, rating_id, FROM films ";
Никита, спасибо за дельные советы! Я долго не могла понять как объединить все запросы в один, включая жанры, получилось запустить, но есть сомнения по поводу метода mapRowToFilms, хорошо ли я сделала, что сборку фильмов делаю вместе с жанрами и рейтингом в одном методе? И еще появился вопрос по поводу запросов на добавление. Если на получение данных лучше делать один общий запрос, то и на добавление в базу тоже лучше один запрос делать или в этом случае не критично?

2023-04-26 11:37 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDbStorage.java
> +        String sqlQueryFilms = "SELECT film_id, film_name, description, duration, release_date, rating_id, FROM films ";
Да, сделано отлично! Добавление в данном случае не критично, данных не много там ожидается :)

2023-04-26 11:38 UTC, mikita95 approved these changes
Все сделано отлично. Можно мержить пул-реквест

2023-04-27 00:17 UTC, merged